name: Lint

on:
  push:
    branches: 
      [main, develop]
  pull_request:

jobs:
  phpcs:
    runs-on: ubuntu-latest

    name: PHPCS

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPCS
        run: vendor/bin/phpcs

  phpstan:
    runs-on: ubuntu-latest

    name: PHPStan
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=512M --no-progress
