name: Lint

on:
  push:
    branches: 
      [main, develop]
pull_request:
    branches:
      [main, develop]

jobs:
  phpcs:
    runs-on: ubuntu-latest

    name: PHPCS

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPCS
        run: vendor/bin/phpcs

  phpstan:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.5, 8.4, 8.3, 8.2]

    name: PHPStan - PHP ${{ matrix.php }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=512M --no-progress
